import Head from 'next/head';

import HomeScreen from '@/src/screens/HomeScreen';

import ProductScreen from '@/src/screens/ProductScreen';
import { useState } from 'react';

export default function Home() {
    const [isOpen, setIsOpen] = useState(true);

    return (
        <>
            <Head>
                <title>Dusk&Dawn</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <HomeScreen />
        </>
    );
}
